# Generated by Django 5.2.8 on 2026-02-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_journalentry_prompt_alter_journalentry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(blank=True, choices=[('great', 'Great'), ('good', 'Good'), ('okay', 'Okay'), ('low', 'Low')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
