# Generated by Django 5.2.8 on 2026-08-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_role_therapistprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
